---
# tasks file for maven

- name: install python-software-propeties
  apt:
   name: software-properties-common
   state: present
- name: Add source repository into sources list
  ansible.builtin.apt_repository:
   repo: ppa:webupd8team/java
   state: present
- name: update apt
  apt:
   name: '*'
   state: latest
- name: Install latest version of "openjdk-6-jdk"
  apt:
   name: default-jdk
   state: latest
   install_recommends: no
- name: download maven
  get_url:
   url:  http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
   dest: /opt
- name: untar the maven file
  unarchive:
   src: /opt/apache-maven-3.3.9-bin.tar.gz
   dest: /opt
   remote_src: yes
- name: install maven
  command: sudo update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001
